/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.26.2-g84424fdfd (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.26.2-g84424fdfd"
#endif
#define SDL_REVISION_NUMBER 0
