/*
 * Horizon Robotics
 *
 *  Copyright (C) 2022-2024 Horizon Robotics Inc.
 *  All rights reserved.
 *  Author: zhe01.zhang<zhe01.zhang@horizon.cc>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */
#ifndef __DIAG_LIB_ID_H_
#define __DIAG_LIB_ID_H_

/** @brief Autogen:typedef_FchmId */
typedef enum {
    FchmId_Invalid          =    0, /*Don't change this enum!!!*/
    FchmId_Cmn              =    1, /*Don't change this enum!!!*/
    FchmId_Video            =    2, /*Don't change this enum!!!*/
    FchmId_Vdsp             =    3, /*Don't change this enum!!!*/
    FchmId_Media_Bottom     =    4, /*Don't change this enum!!!*/
    FchmId_Media_Top        =    5, /*Don't change this enum!!!*/
    FchmId_Peri             =    6, /*Don't change this enum!!!*/
    FchmId_Hsi              =    7, /*Don't change this enum!!!*/
    FchmId_Gpu              =    8, /*Don't change this enum!!!*/
    FchmId_Ddr2             =    9, /*Don't change this enum!!!*/
    FchmId_Ddr1             =   10, /*Don't change this enum!!!*/
    FchmId_Ddr0             =   11, /*Don't change this enum!!!*/
    FchmId_Cpe0             =   12, /*Don't change this enum!!!*/
    FchmId_Cpe1             =   13, /*Don't change this enum!!!*/
    FchmId_Cpe_Lite         =   14, /*Don't change this enum!!!*/
    FchmId_Cam              =   15, /*Don't change this enum!!!*/
    FchmId_Bpu              =   16, /*Don't change this enum!!!*/
    FchmId_Bpu_Hpy          =   17, /*Don't change this enum!!!*/
    FchmId_Bpu_Vm1          =   18, /*Don't change this enum!!!*/
    FchmId_Bpu_Vm0          =   19, /*Don't change this enum!!!*/
    FchmId_Bpu_Pwr          =   20, /*Don't change this enum!!!*/
    FchmId_Cpu_Mp4          =   21, /*Don't change this enum!!!*/
    FchmId_Cpu_Mp2          =   22, /*Don't change this enum!!!*/
    FchmId_Mcu              =   23, /*Don't change this enum!!!*/
    FchmId_Mcu_Peri         =   24, /*Don't change this enum!!!*/
    FchmId_Hsm              =   25, /*Don't change this enum!!!*/
}Hobot_FchmId;

/** @brief Autogen:typedef_ModuleId */
typedef enum {
    ModuleId_Invalid    =  0,    /*0 Don't change this enum!!!*/
    ModuleId_AcoreDiag0 =  1,    /*1 Don't change this enum!!!*/
    ModuleId_AcoreDiag1,        /*2 Don't change this enum!!!*/
    ModuleId_McuDiag0,          /*3 Don't change this enum!!!*/
    ModuleId_McuDiag1,          /*4 Don't change this enum!!!*/
    ModuleId_AcoreTick0,        /*5 Don't change this enum!!!*/
    ModuleId_AcoreTick1,        /*6 Don't change this enum!!!*/
    ModuleId_McuTick0,          /*7 Don't change this enum!!!*/
    ModuleId_McuTick1,          /*8 Don't change this enum!!!*/
    ModuleId_McuTick2,          /*9 Don't change this enum!!!*/
    ModuleId_MaskFault0,        /*10 Don't change this enum!!!*/
    ModuleId_AcoreStartFail0,   /*11 Don't change this enum!!!*/
    ModuleId_AcorePanic0,       /*12 Don't change this enum!!!*/
    ModuleId_SwRsved0,          /*13 Don't change this enum!!!*/
    ModuleId_SwRsved1,          /*14 Don't change this enum!!!*/
    ModuleId_SwRsved2,          /*15 Don't change this enum!!!*/
    ModuleId_HwStart,           /*16 Don't change this enum!!!*/
    ModuleId_Cim0 = ModuleId_HwStart,    /*16 Don't change this enum!!!*/
    ModuleId_Cim1,              /*17 Don't change this enum!!!*/
    ModuleId_Cim2,              /*18 Don't change this enum!!!*/
    ModuleId_Cim3,              /*19 Don't change this enum!!!*/
    ModuleId_Cim4,              /*20 Don't change this enum!!!*/
    ModuleId_Cim5,              /*21 Don't change this enum!!!*/
    ModuleId_Cmm0,              /*22 Don't change this enum!!!*/
    ModuleId_Cmm1,              /*23 Don't change this enum!!!*/
    ModuleId_Cmm2,              /*24 Don't change this enum!!!*/
    ModuleId_Cmm3,              /*25 Don't change this enum!!!*/
    ModuleId_Cmm4,              /*26 Don't change this enum!!!*/
    ModuleId_Cmm5,              /*27 Don't change this enum!!!*/
    ModuleId_Cmm6,              /*28 Don't change this enum!!!*/
    ModuleId_Cmm7,              /*29 Don't change this enum!!!*/
    ModuleId_Cmm8,              /*30 Don't change this enum!!!*/
    ModuleId_Cmm9,              /*31 Don't change this enum!!!*/
    ModuleId_Cmm10,             /*32 Don't change this enum!!!*/
    ModuleId_Cmm11,             /*33 Don't change this enum!!!*/
    ModuleId_Cmm12,             /*34 Don't change this enum!!!*/
    ModuleId_Cmm13,             /*35 Don't change this enum!!!*/
    ModuleId_Cmm14,             /*36 Don't change this enum!!!*/
    ModuleId_Cmm15,             /*37 Don't change this enum!!!*/
    ModuleId_Cmm16,             /*38 Don't change this enum!!!*/
    ModuleId_Cmm17,             /*39 Don't change this enum!!!*/
    ModuleId_Cmm18,             /*40 Don't change this enum!!!*/
    ModuleId_Cmm19,             /*41 Don't change this enum!!!*/
    ModuleId_Cmm20,             /*42 Don't change this enum!!!*/
    ModuleId_Cmm21,             /*43 Don't change this enum!!!*/
    ModuleId_Cmm22,             /*44 Don't change this enum!!!*/
    ModuleId_Cmm23,             /*45 Don't change this enum!!!*/
    ModuleId_Cmm24,             /*46 Don't change this enum!!!*/
    ModuleId_Cmm25,             /*47 Don't change this enum!!!*/
    ModuleId_Cmm26,             /*48 Don't change this enum!!!*/
    ModuleId_Cmm27,             /*49 Don't change this enum!!!*/
    ModuleId_Cmm28,             /*50 Don't change this enum!!!*/
    ModuleId_Cmm29,             /*51 Don't change this enum!!!*/
    ModuleId_Cmm30,             /*52 Don't change this enum!!!*/
    ModuleId_Cmm31,             /*53 Don't change this enum!!!*/
    ModuleId_Cmm32,             /*54 Don't change this enum!!!*/
    ModuleId_Cmm33,             /*55 Don't change this enum!!!*/
    ModuleId_Cmm34,             /*56 Don't change this enum!!!*/
    ModuleId_Cmm35,             /*57 Don't change this enum!!!*/
    ModuleId_Clock0,            /*58 Don't change this enum!!!*/
    ModuleId_Clock1,            /*59 Don't change this enum!!!*/
    ModuleId_Clock2,            /*60 Don't change this enum!!!*/
    ModuleId_Clock3,            /*61 Don't change this enum!!!*/
    ModuleId_Clock4,            /*62 Don't change this enum!!!*/
    ModuleId_Clock5,            /*63 Don't change this enum!!!*/
    ModuleId_Clock6,            /*64 Don't change this enum!!!*/
    ModuleId_Clock7,            /*65 Don't change this enum!!!*/
    ModuleId_Clock8,            /*66 Don't change this enum!!!*/
    ModuleId_Clock9,            /*67 Don't change this enum!!!*/
    ModuleId_Clock10,           /*68 Don't change this enum!!!*/
    ModuleId_Clock11,           /*69 Don't change this enum!!!*/
    ModuleId_Clock12,           /*70 Don't change this enum!!!*/
    ModuleId_Clock13,           /*71 Don't change this enum!!!*/
    ModuleId_Clock14,           /*72 Don't change this enum!!!*/
    ModuleId_Clock15,           /*73 Don't change this enum!!!*/
    ModuleId_Clock16,           /*74 Don't change this enum!!!*/
    ModuleId_Clock17,           /*75 Don't change this enum!!!*/
    ModuleId_Clock18,           /*76 Don't change this enum!!!*/
    ModuleId_Clock19,           /*77 Don't change this enum!!!*/
    ModuleId_Clock20,           /*78 Don't change this enum!!!*/
    ModuleId_Clock21,           /*79 Don't change this enum!!!*/
    ModuleId_Clock22,           /*80 Don't change this enum!!!*/
    ModuleId_Clock23,           /*81 Don't change this enum!!!*/
    ModuleId_Clock24,           /*82 Don't change this enum!!!*/
    ModuleId_Clock25,           /*83 Don't change this enum!!!*/
    ModuleId_Clock26,           /*84 Don't change this enum!!!*/
    ModuleId_Clock27,           /*85 Don't change this enum!!!*/
    ModuleId_Clock28,           /*86 Don't change this enum!!!*/
    ModuleId_Clock29,           /*87 Don't change this enum!!!*/
    ModuleId_Clock30,           /*88 Don't change this enum!!!*/
    ModuleId_Clock31,           /*89 Don't change this enum!!!*/
    ModuleId_Clock32,           /*90 Don't change this enum!!!*/
    ModuleId_Clock33,           /*91 Don't change this enum!!!*/
    ModuleId_Clock34,           /*92 Don't change this enum!!!*/
    ModuleId_Clock35,           /*93 Don't change this enum!!!*/
    ModuleId_Dpi2ipi0,          /*94 Don't change this enum!!!*/
    ModuleId_Dpi2ipi1,          /*95 Don't change this enum!!!*/
    ModuleId_Fchm0,             /*96 Don't change this enum!!!*/
    ModuleId_Fchm1,             /*97 Don't change this enum!!!*/
    ModuleId_Fchm2,             /*98 Don't change this enum!!!*/
    ModuleId_Fchm3,             /*99 Don't change this enum!!!*/
    ModuleId_Fchm4,             /*100 Don't change this enum!!!*/
    ModuleId_Fchm5,             /*101 Don't change this enum!!!*/
    ModuleId_Fchm6,             /*102 Don't change this enum!!!*/
    ModuleId_Fchm7,             /*103 Don't change this enum!!!*/
    ModuleId_Fchm8,             /*104 Don't change this enum!!!*/
    ModuleId_Fchm9,             /*105 Don't change this enum!!!*/
    ModuleId_Fchm10,            /*106 Don't change this enum!!!*/
    ModuleId_Fchm11,            /*107 Don't change this enum!!!*/
    ModuleId_Fchm12,            /*108 Don't change this enum!!!*/
    ModuleId_Fchm13,            /*109 Don't change this enum!!!*/
    ModuleId_Fchm14,            /*110 Don't change this enum!!!*/
    ModuleId_Fchm15,            /*111 Don't change this enum!!!*/
    ModuleId_Fchm16,            /*112 Don't change this enum!!!*/
    ModuleId_Fchm17,            /*113 Don't change this enum!!!*/
    ModuleId_Fchm18,            /*114 Don't change this enum!!!*/
    ModuleId_Fchm19,            /*115 Don't change this enum!!!*/
    ModuleId_Fchm20,            /*116 Don't change this enum!!!*/
    ModuleId_Fchm21,            /*117 Don't change this enum!!!*/
    ModuleId_Fchm22,            /*118 Don't change this enum!!!*/
    ModuleId_Fchm23,            /*119 Don't change this enum!!!*/
    ModuleId_Fchm24,            /*120 Don't change this enum!!!*/
    ModuleId_Fchm25,            /*121 Don't change this enum!!!*/
    ModuleId_Fchm26,            /*122 Don't change this enum!!!*/
    ModuleId_Fchm27,            /*123 Don't change this enum!!!*/
    ModuleId_Fchm28,            /*124 Don't change this enum!!!*/
    ModuleId_Fchm29,            /*125 Don't change this enum!!!*/
    ModuleId_Fchm30,            /*126 Don't change this enum!!!*/
    ModuleId_Fchm31,            /*127 Don't change this enum!!!*/
    ModuleId_Fchm32,            /*128 Don't change this enum!!!*/
    ModuleId_Fchm33,            /*129 Don't change this enum!!!*/
    ModuleId_Fchm34,            /*130 Don't change this enum!!!*/
    ModuleId_Fchm35,            /*131 Don't change this enum!!!*/
    ModuleId_Firewall0,         /*132 Don't change this enum!!!*/
    ModuleId_Firewall1,         /*133 Don't change this enum!!!*/
    ModuleId_Firewall2,         /*134 Don't change this enum!!!*/
    ModuleId_Firewall3,         /*135 Don't change this enum!!!*/
    ModuleId_Firewall4,         /*136 Don't change this enum!!!*/
    ModuleId_Firewall5,         /*137 Don't change this enum!!!*/
    ModuleId_Firewall6,         /*138 Don't change this enum!!!*/
    ModuleId_Firewall7,         /*139 Don't change this enum!!!*/
    ModuleId_Firewall8,         /*140 Don't change this enum!!!*/
    ModuleId_Firewall9,         /*141 Don't change this enum!!!*/
    ModuleId_Firewall10,        /*142 Don't change this enum!!!*/
    ModuleId_Firewall11,        /*143 Don't change this enum!!!*/
    ModuleId_Firewall12,        /*144 Don't change this enum!!!*/
    ModuleId_Firewall13,        /*145 Don't change this enum!!!*/
    ModuleId_Firewall14,        /*146 Don't change this enum!!!*/
    ModuleId_Firewall15,        /*147 Don't change this enum!!!*/
    ModuleId_Firewall16,        /*148 Don't change this enum!!!*/
    ModuleId_Firewall17,        /*149 Don't change this enum!!!*/
    ModuleId_Firewall18,        /*150 Don't change this enum!!!*/
    ModuleId_Firewall19,        /*151 Don't change this enum!!!*/
    ModuleId_Firewall20,        /*152 Don't change this enum!!!*/
    ModuleId_Firewall21,        /*153 Don't change this enum!!!*/
    ModuleId_Firewall22,        /*154 Don't change this enum!!!*/
    ModuleId_Firewall23,        /*155 Don't change this enum!!!*/
    ModuleId_Firewall24,        /*156 Don't change this enum!!!*/
    ModuleId_Firewall25,        /*157 Don't change this enum!!!*/
    ModuleId_Firewall26,        /*158 Don't change this enum!!!*/
    ModuleId_Firewall27,        /*159 Don't change this enum!!!*/
    ModuleId_Firewall28,        /*160 Don't change this enum!!!*/
    ModuleId_Firewall29,        /*161 Don't change this enum!!!*/
    ModuleId_Firewall30,        /*162 Don't change this enum!!!*/
    ModuleId_Firewall31,        /*163 Don't change this enum!!!*/
    ModuleId_Firewall32,        /*164 Don't change this enum!!!*/
    ModuleId_Firewall33,        /*165 Don't change this enum!!!*/
    ModuleId_Firewall34,        /*166 Don't change this enum!!!*/
    ModuleId_Firewall35,        /*167 Don't change this enum!!!*/
    ModuleId_Bdisolation0,      /*168 Don't change this enum!!!*/
    ModuleId_Bdisolation1,      /*169 Don't change this enum!!!*/
    ModuleId_Bdisolation2,      /*170 Don't change this enum!!!*/
    ModuleId_Bdisolation3,      /*171 Don't change this enum!!!*/
    ModuleId_Sram0,             /*172 Don't change this enum!!!*/
    ModuleId_Sram1,             /*173 Don't change this enum!!!*/
    ModuleId_Sram2,             /*174 Don't change this enum!!!*/
    ModuleId_Sram3,             /*175 Don't change this enum!!!*/
    ModuleId_Sram4,             /*176 Don't change this enum!!!*/
    ModuleId_Sram5,             /*177 Don't change this enum!!!*/
    ModuleId_Lpwm0,             /*178 Don't change this enum!!!*/
    ModuleId_Lpwm1,             /*179 Don't change this enum!!!*/
    ModuleId_Lpwm2,             /*180 Don't change this enum!!!*/
    ModuleId_Lpwm3,             /*181 Don't change this enum!!!*/
    ModuleId_Otfcrc0,           /*182 Don't change this enum!!!*/
    ModuleId_Otfcrc1,           /*183 Don't change this enum!!!*/
    ModuleId_Otfcrc2,           /*184 Don't change this enum!!!*/
    ModuleId_Pmu0,              /*185 Don't change this enum!!!*/
    ModuleId_Pmu1,              /*186 Don't change this enum!!!*/
    ModuleId_Pmu2,              /*187 Don't change this enum!!!*/
    ModuleId_Pmu3,              /*188 Don't change this enum!!!*/
    ModuleId_Pmu4,              /*189 Don't change this enum!!!*/
    ModuleId_Pmu5,              /*190 Don't change this enum!!!*/
    ModuleId_Pmu6,              /*191 Don't change this enum!!!*/
    ModuleId_Pmu7,              /*192 Don't change this enum!!!*/
    ModuleId_Pmu8,              /*193 Don't change this enum!!!*/
    ModuleId_Pmu9,              /*194 Don't change this enum!!!*/
    ModuleId_Pmu10,             /*195 Don't change this enum!!!*/
    ModuleId_Pmu11,             /*196 Don't change this enum!!!*/
    ModuleId_Pmu12,             /*197 Don't change this enum!!!*/
    ModuleId_Pmu13,             /*198 Don't change this enum!!!*/
    ModuleId_Pmu14,             /*199 Don't change this enum!!!*/
    ModuleId_Pmu15,             /*200 Don't change this enum!!!*/
    ModuleId_Pmu16,             /*201 Don't change this enum!!!*/
    ModuleId_Pmu17,             /*202 Don't change this enum!!!*/
    ModuleId_Pmu18,             /*203 Don't change this enum!!!*/
    ModuleId_Pmu19,             /*204 Don't change this enum!!!*/
    ModuleId_Pmu20,             /*205 Don't change this enum!!!*/
    ModuleId_Pmu21,             /*206 Don't change this enum!!!*/
    ModuleId_Pmu22,             /*207 Don't change this enum!!!*/
    ModuleId_Pmu23,             /*208 Don't change this enum!!!*/
    ModuleId_Pmu24,             /*209 Don't change this enum!!!*/
    ModuleId_Pmu25,             /*210 Don't change this enum!!!*/
    ModuleId_Pmu26,             /*211 Don't change this enum!!!*/
    ModuleId_Pmu27,             /*212 Don't change this enum!!!*/
    ModuleId_Pmu28,             /*213 Don't change this enum!!!*/
    ModuleId_Pmu29,             /*214 Don't change this enum!!!*/
    ModuleId_Pmu30,             /*215 Don't change this enum!!!*/
    ModuleId_Pmu31,             /*216 Don't change this enum!!!*/
    ModuleId_Pmu32,             /*217 Don't change this enum!!!*/
    ModuleId_Pmu33,             /*218 Don't change this enum!!!*/
    ModuleId_Pmu34,             /*219 Don't change this enum!!!*/
    ModuleId_Pmu35,             /*220 Don't change this enum!!!*/
    ModuleId_Pwm0,              /*221 Don't change this enum!!!*/
    ModuleId_Pwm1,              /*222 Don't change this enum!!!*/
    ModuleId_Pwm2,              /*223 Don't change this enum!!!*/
    ModuleId_Pyramid0,          /*224 Don't change this enum!!!*/
    ModuleId_Pyramid1,          /*225 Don't change this enum!!!*/
    ModuleId_Pyramid2,          /*226 Don't change this enum!!!*/
    ModuleId_Pyramid3,          /*227 Don't change this enum!!!*/
    ModuleId_Pyramid4,          /*228 Don't change this enum!!!*/
    ModuleId_Pyramid5,          /*229 Don't change this enum!!!*/
    ModuleId_Rst0,              /*230 Don't change this enum!!!*/
    ModuleId_Rst1,              /*231 Don't change this enum!!!*/
    ModuleId_Rst2,              /*232 Don't change this enum!!!*/
    ModuleId_Rst3,              /*233 Don't change this enum!!!*/
    ModuleId_Rst4,              /*234 Don't change this enum!!!*/
    ModuleId_Rst5,              /*235 Don't change this enum!!!*/
    ModuleId_Rst6,              /*236 Don't change this enum!!!*/
    ModuleId_Rst7,              /*237 Don't change this enum!!!*/
    ModuleId_Rst8,              /*238 Don't change this enum!!!*/
    ModuleId_Rst9,              /*239 Don't change this enum!!!*/
    ModuleId_Rst10,             /*240 Don't change this enum!!!*/
    ModuleId_Rst11,             /*241 Don't change this enum!!!*/
    ModuleId_Rst12,             /*242 Don't change this enum!!!*/
    ModuleId_Rst13,             /*243 Don't change this enum!!!*/
    ModuleId_Rst14,             /*244 Don't change this enum!!!*/
    ModuleId_Rst15,             /*245 Don't change this enum!!!*/
    ModuleId_Rst16,             /*246 Don't change this enum!!!*/
    ModuleId_Rst17,             /*247 Don't change this enum!!!*/
    ModuleId_Rst18,             /*248 Don't change this enum!!!*/
    ModuleId_Rst19,             /*249 Don't change this enum!!!*/
    ModuleId_Rst20,             /*250 Don't change this enum!!!*/
    ModuleId_Rst21,             /*251 Don't change this enum!!!*/
    ModuleId_Rst22,             /*252 Don't change this enum!!!*/
    ModuleId_Rst23,             /*253 Don't change this enum!!!*/
    ModuleId_Rst24,             /*254 Don't change this enum!!!*/
    ModuleId_Rst25,             /*255 Don't change this enum!!!*/
    ModuleId_Rst26,             /*256 Don't change this enum!!!*/
    ModuleId_Rst27,             /*257 Don't change this enum!!!*/
    ModuleId_Rst28,             /*258 Don't change this enum!!!*/
    ModuleId_Rst29,             /*259 Don't change this enum!!!*/
    ModuleId_Rst30,             /*260 Don't change this enum!!!*/
    ModuleId_Rst31,             /*261 Don't change this enum!!!*/
    ModuleId_Rst32,             /*262 Don't change this enum!!!*/
    ModuleId_Rst33,             /*263 Don't change this enum!!!*/
    ModuleId_Rst34,             /*264 Don't change this enum!!!*/
    ModuleId_Rst35,             /*265 Don't change this enum!!!*/
    ModuleId_Rtc0,              /*266 Don't change this enum!!!*/
    ModuleId_Stcu0,             /*267 Don't change this enum!!!*/
    ModuleId_Stcu1,             /*268 Don't change this enum!!!*/
    ModuleId_Stcu2,             /*269 Don't change this enum!!!*/
    ModuleId_Stcu3,             /*270 Don't change this enum!!!*/
    ModuleId_Stcu4,             /*271 Don't change this enum!!!*/
    ModuleId_Stcu5,             /*272 Don't change this enum!!!*/
    ModuleId_Stcu6,             /*273 Don't change this enum!!!*/
    ModuleId_Stcu7,             /*274 Don't change this enum!!!*/
    ModuleId_Stcu8,             /*275 Don't change this enum!!!*/
    ModuleId_Stcu9,             /*276 Don't change this enum!!!*/
    ModuleId_Stcu10,            /*277 Don't change this enum!!!*/
    ModuleId_Stcu11,            /*278 Don't change this enum!!!*/
    ModuleId_Stcu12,            /*279 Don't change this enum!!!*/
    ModuleId_Stcu13,            /*280 Don't change this enum!!!*/
    ModuleId_Stcu14,            /*281 Don't change this enum!!!*/
    ModuleId_Stcu15,            /*282 Don't change this enum!!!*/
    ModuleId_Stcu16,            /*283 Don't change this enum!!!*/
    ModuleId_Stcu17,            /*284 Don't change this enum!!!*/
    ModuleId_Stcu18,            /*285 Don't change this enum!!!*/
    ModuleId_Stcu19,            /*286 Don't change this enum!!!*/
    ModuleId_Stcu20,            /*287 Don't change this enum!!!*/
    ModuleId_Stcu21,            /*288 Don't change this enum!!!*/
    ModuleId_Stcu22,            /*289 Don't change this enum!!!*/
    ModuleId_Stcu23,            /*290 Don't change this enum!!!*/
    ModuleId_Stcu24,            /*291 Don't change this enum!!!*/
    ModuleId_Stcu25,            /*292 Don't change this enum!!!*/
    ModuleId_Stcu26,            /*293 Don't change this enum!!!*/
    ModuleId_Stcu27,            /*294 Don't change this enum!!!*/
    ModuleId_Stcu28,            /*295 Don't change this enum!!!*/
    ModuleId_Stcu29,            /*296 Don't change this enum!!!*/
    ModuleId_Stcu30,            /*297 Don't change this enum!!!*/
    ModuleId_Stcu31,            /*298 Don't change this enum!!!*/
    ModuleId_Stcu32,            /*299 Don't change this enum!!!*/
    ModuleId_Stcu33,            /*300 Don't change this enum!!!*/
    ModuleId_Stcu34,            /*301 Don't change this enum!!!*/
    ModuleId_Stcu35,            /*302 Don't change this enum!!!*/
    ModuleId_Stitch0,           /*303 Don't change this enum!!!*/
    ModuleId_Timer0,            /*304 Don't change this enum!!!*/
    ModuleId_Timer1,            /*305 Don't change this enum!!!*/
    ModuleId_Timer2,            /*306 Don't change this enum!!!*/
    ModuleId_Timer3,            /*307 Don't change this enum!!!*/
    ModuleId_Timer4,            /*308 Don't change this enum!!!*/
    ModuleId_Timer5,            /*309 Don't change this enum!!!*/
    ModuleId_Timer6,            /*310 Don't change this enum!!!*/
    ModuleId_Timer7,            /*311 Don't change this enum!!!*/
    ModuleId_Timer8,            /*312 Don't change this enum!!!*/
    ModuleId_Timer9,            /*313 Don't change this enum!!!*/
    ModuleId_Timer10,           /*314 Don't change this enum!!!*/
    ModuleId_Timer11,           /*315 Don't change this enum!!!*/
    ModuleId_Timer12,           /*316 Don't change this enum!!!*/
    ModuleId_Timer13,           /*317 Don't change this enum!!!*/
    ModuleId_Timer14,           /*318 Don't change this enum!!!*/
    ModuleId_Timer15,           /*319 Don't change this enum!!!*/
    ModuleId_Timer16,           /*320 Don't change this enum!!!*/
    ModuleId_Timer17,           /*321 Don't change this enum!!!*/
    ModuleId_Timer18,           /*322 Don't change this enum!!!*/
    ModuleId_Timer19,           /*323 Don't change this enum!!!*/
    ModuleId_Timer20,           /*324 Don't change this enum!!!*/
    ModuleId_Timer21,           /*325 Don't change this enum!!!*/
    ModuleId_Timer22,           /*326 Don't change this enum!!!*/
    ModuleId_Timer23,           /*327 Don't change this enum!!!*/
    ModuleId_Ynr0,              /*328 Don't change this enum!!!*/
    ModuleId_Hwspinlock0,       /*329 Don't change this enum!!!*/
    ModuleId_Hwspinlock1,       /*330 Don't change this enum!!!*/
    ModuleId_Hwspinlock2,       /*331 Don't change this enum!!!*/
    ModuleId_Hwspinlock3,       /*332 Don't change this enum!!!*/
    ModuleId_Hwspinlock4,       /*333 Don't change this enum!!!*/
    ModuleId_Hwspinlock5,       /*334 Don't change this enum!!!*/
    ModuleId_Idu0,              /*335 Don't change this enum!!!*/
    ModuleId_Idu1,              /*336 Don't change this enum!!!*/
    ModuleId_Litemmu0,          /*337 Don't change this enum!!!*/
    ModuleId_Pdma0,             /*338 Don't change this enum!!!*/
    ModuleId_Pdma1,             /*339 Don't change this enum!!!*/
    ModuleId_Subsysreg0,        /*340 Don't change this enum!!!*/
    ModuleId_Subsysreg1,        /*341 Don't change this enum!!!*/
    ModuleId_Subsysreg2,        /*342 Don't change this enum!!!*/
    ModuleId_Subsysreg3,        /*343 Don't change this enum!!!*/
    ModuleId_Subsysreg4,        /*344 Don't change this enum!!!*/
    ModuleId_Subsysreg5,        /*345 Don't change this enum!!!*/
    ModuleId_Subsysreg6,        /*346 Don't change this enum!!!*/
    ModuleId_Subsysreg7,        /*347 Don't change this enum!!!*/
    ModuleId_Subsysreg8,        /*348 Don't change this enum!!!*/
    ModuleId_Subsysreg9,        /*349 Don't change this enum!!!*/
    ModuleId_Subsysreg10,       /*350 Don't change this enum!!!*/
    ModuleId_Subsysreg11,       /*351 Don't change this enum!!!*/
    ModuleId_Subsysreg12,       /*352 Don't change this enum!!!*/
    ModuleId_Subsysreg13,       /*353 Don't change this enum!!!*/
    ModuleId_Subsysreg14,       /*354 Don't change this enum!!!*/
    ModuleId_Subsysreg15,       /*355 Don't change this enum!!!*/
    ModuleId_Subsysreg16,       /*356 Don't change this enum!!!*/
    ModuleId_Subsysreg17,       /*357 Don't change this enum!!!*/
    ModuleId_Subsysreg18,       /*358 Don't change this enum!!!*/
    ModuleId_Subsysreg19,       /*359 Don't change this enum!!!*/
    ModuleId_Subsysreg20,       /*360 Don't change this enum!!!*/
    ModuleId_Subsysreg21,       /*361 Don't change this enum!!!*/
    ModuleId_Subsysreg22,       /*362 Don't change this enum!!!*/
    ModuleId_Subsysreg23,       /*363 Don't change this enum!!!*/
    ModuleId_Subsysreg24,       /*364 Don't change this enum!!!*/
    ModuleId_Subsysreg25,       /*365 Don't change this enum!!!*/
    ModuleId_Subsysreg26,       /*366 Don't change this enum!!!*/
    ModuleId_Subsysreg27,       /*367 Don't change this enum!!!*/
    ModuleId_Subsysreg28,       /*368 Don't change this enum!!!*/
    ModuleId_Subsysreg29,       /*369 Don't change this enum!!!*/
    ModuleId_Subsysreg30,       /*370 Don't change this enum!!!*/
    ModuleId_Subsysreg31,       /*371 Don't change this enum!!!*/
    ModuleId_Subsysreg32,       /*372 Don't change this enum!!!*/
    ModuleId_Subsysreg33,       /*373 Don't change this enum!!!*/
    ModuleId_Subsysreg34,       /*374 Don't change this enum!!!*/
    ModuleId_Subsysreg35,       /*375 Don't change this enum!!!*/
    ModuleId_Bpu0,              /*376 Don't change this enum!!!*/
    ModuleId_Bpu1,              /*377 Don't change this enum!!!*/
    ModuleId_Bpu2,              /*378 Don't change this enum!!!*/
    ModuleId_Dsuae0,            /*379 Don't change this enum!!!*/
    ModuleId_Dsuae1,            /*380 Don't change this enum!!!*/
    ModuleId_Dsuae2,            /*381 Don't change this enum!!!*/
    ModuleId_Dsuae3,            /*382 Don't change this enum!!!*/
    ModuleId_Swfault0,          /*383 Don't change this enum!!!*/
    ModuleId_Swfault1,          /*384 Don't change this enum!!!*/
    ModuleId_Swfault2,          /*385 Don't change this enum!!!*/
    ModuleId_Swfault3,          /*386 Don't change this enum!!!*/
    ModuleId_Swfault4,          /*387 Don't change this enum!!!*/
    ModuleId_Swfault5,          /*388 Don't change this enum!!!*/
    ModuleId_Swfault6,          /*389 Don't change this enum!!!*/
    ModuleId_Swfault7,          /*390 Don't change this enum!!!*/
    ModuleId_Swfault8,          /*391 Don't change this enum!!!*/
    ModuleId_Swfault9,          /*392 Don't change this enum!!!*/
    ModuleId_Swfault10,         /*393 Don't change this enum!!!*/
    ModuleId_Swfault11,         /*394 Don't change this enum!!!*/
    ModuleId_Swfault12,         /*395 Don't change this enum!!!*/
    ModuleId_Swfault13,         /*396 Don't change this enum!!!*/
    ModuleId_Swfault14,         /*397 Don't change this enum!!!*/
    ModuleId_Swfault15,         /*398 Don't change this enum!!!*/
    ModuleId_Swfault16,         /*399 Don't change this enum!!!*/
    ModuleId_Swfault17,         /*400 Don't change this enum!!!*/
    ModuleId_Swfault18,         /*401 Don't change this enum!!!*/
    ModuleId_Swfault19,         /*402 Don't change this enum!!!*/
    ModuleId_Swfault20,         /*403 Don't change this enum!!!*/
    ModuleId_Swfault21,         /*404 Don't change this enum!!!*/
    ModuleId_Swfault22,         /*405 Don't change this enum!!!*/
    ModuleId_Swfault23,         /*406 Don't change this enum!!!*/
    ModuleId_Swfault24,         /*407 Don't change this enum!!!*/
    ModuleId_Swfault25,         /*408 Don't change this enum!!!*/
    ModuleId_Swfault26,         /*409 Don't change this enum!!!*/
    ModuleId_Swfault27,         /*410 Don't change this enum!!!*/
    ModuleId_Swfault28,         /*411 Don't change this enum!!!*/
    ModuleId_Swfault29,         /*412 Don't change this enum!!!*/
    ModuleId_Swfault30,         /*413 Don't change this enum!!!*/
    ModuleId_Swfault31,         /*414 Don't change this enum!!!*/
    ModuleId_Swfault32,         /*415 Don't change this enum!!!*/
    ModuleId_Swfault33,         /*416 Don't change this enum!!!*/
    ModuleId_Swfault34,         /*417 Don't change this enum!!!*/
    ModuleId_Swfault35,         /*418 Don't change this enum!!!*/
    ModuleId_A78ae0,            /*419 Don't change this enum!!!*/
    ModuleId_A78ae1,            /*420 Don't change this enum!!!*/
    ModuleId_A78ae2,            /*421 Don't change this enum!!!*/
    ModuleId_A78ae3,            /*422 Don't change this enum!!!*/
    ModuleId_A78ae4,            /*423 Don't change this enum!!!*/
    ModuleId_A78ae5,            /*424 Don't change this enum!!!*/
    ModuleId_A78ae6,            /*425 Don't change this enum!!!*/
    ModuleId_A78ae7,            /*426 Don't change this enum!!!*/
    ModuleId_A78ae8,            /*427 Don't change this enum!!!*/
    ModuleId_A78ae9,            /*428 Don't change this enum!!!*/
    ModuleId_A78ae10,           /*429 Don't change this enum!!!*/
    ModuleId_A78ae11,           /*430 Don't change this enum!!!*/
    ModuleId_A78ae12,           /*431 Don't change this enum!!!*/
    ModuleId_A78ae13,           /*432 Don't change this enum!!!*/
    ModuleId_Adc0,              /*433 Don't change this enum!!!*/
    ModuleId_Adc1,              /*434 Don't change this enum!!!*/
    ModuleId_Canfd0,            /*435 Don't change this enum!!!*/
    ModuleId_Canfd1,            /*436 Don't change this enum!!!*/
    ModuleId_Cmn0,              /*437 Don't change this enum!!!*/
    ModuleId_Ddr0,              /*438 Don't change this enum!!!*/
    ModuleId_Ddr1,              /*439 Don't change this enum!!!*/
    ModuleId_Ddr2,              /*440 Don't change this enum!!!*/
    ModuleId_Ddr3,              /*441 Don't change this enum!!!*/
    ModuleId_Ddr4,              /*442 Don't change this enum!!!*/
    ModuleId_Ddr5,              /*443 Don't change this enum!!!*/
    ModuleId_Mdma0,             /*444 Don't change this enum!!!*/
    ModuleId_Mdma1,             /*445 Don't change this enum!!!*/
    ModuleId_Mdma2,             /*446 Don't change this enum!!!*/
    ModuleId_Mdma3,             /*447 Don't change this enum!!!*/
    ModuleId_Mdma4,             /*448 Don't change this enum!!!*/
    ModuleId_Mdma5,             /*449 Don't change this enum!!!*/
    ModuleId_Mdma6,             /*450 Don't change this enum!!!*/
    ModuleId_Mdma7,             /*451 Don't change this enum!!!*/
    ModuleId_Gmac0,             /*452 Don't change this enum!!!*/
    ModuleId_Gmac1,             /*453 Don't change this enum!!!*/
    ModuleId_Gmac2,             /*454 Don't change this enum!!!*/
    ModuleId_Gmac3,             /*455 Don't change this enum!!!*/
    ModuleId_Xgmac0,            /*456 Don't change this enum!!!*/
    ModuleId_Xgmac1,            /*457 Don't change this enum!!!*/
    ModuleId_Xgmac2,            /*458 Don't change this enum!!!*/
    ModuleId_Xgmac3,            /*459 Don't change this enum!!!*/
    ModuleId_Xpcs0,             /*460 Don't change this enum!!!*/
    ModuleId_Xpcs1,             /*461 Don't change this enum!!!*/
    ModuleId_Xpcs2,             /*462 Don't change this enum!!!*/
    ModuleId_Xpcs3,             /*463 Don't change this enum!!!*/
    ModuleId_Xpcs4,             /*464 Don't change this enum!!!*/
    ModuleId_Xpcs5,             /*465 Don't change this enum!!!*/
    ModuleId_Xpcs6,             /*466 Don't change this enum!!!*/
    ModuleId_Xpcs7,             /*467 Don't change this enum!!!*/
    ModuleId_Gic0,              /*468 Don't change this enum!!!*/
    ModuleId_Gic1,              /*469 Don't change this enum!!!*/
    ModuleId_Gic2,              /*470 Don't change this enum!!!*/
    ModuleId_Gpio0,             /*471 Don't change this enum!!!*/
    ModuleId_Gpio1,             /*472 Don't change this enum!!!*/
    ModuleId_Gpio2,             /*473 Don't change this enum!!!*/
    ModuleId_Gpio3,             /*474 Don't change this enum!!!*/
    ModuleId_Gpu0,              /*475 Don't change this enum!!!*/
    ModuleId_I2c0,              /*476 Don't change this enum!!!*/
    ModuleId_I2c1,              /*477 Don't change this enum!!!*/
    ModuleId_I2c2,              /*478 Don't change this enum!!!*/
    ModuleId_I2c3,              /*479 Don't change this enum!!!*/
    ModuleId_I2c4,              /*480 Don't change this enum!!!*/
    ModuleId_I2c5,              /*481 Don't change this enum!!!*/
    ModuleId_I2c6,              /*482 Don't change this enum!!!*/
    ModuleId_I2c7,              /*483 Don't change this enum!!!*/
    ModuleId_I2c8,              /*484 Don't change this enum!!!*/
    ModuleId_I2c9,              /*485 Don't change this enum!!!*/
    ModuleId_I2c10,             /*486 Don't change this enum!!!*/
    ModuleId_I2c11,             /*487 Don't change this enum!!!*/
    ModuleId_I2c12,             /*488 Don't change this enum!!!*/
    ModuleId_I2c13,             /*489 Don't change this enum!!!*/
    ModuleId_I2c14,             /*490 Don't change this enum!!!*/
    ModuleId_Mailbox0,          /*491 Don't change this enum!!!*/
    ModuleId_Mailbox1,          /*492 Don't change this enum!!!*/
    ModuleId_Mailbox2,          /*493 Don't change this enum!!!*/
    ModuleId_Mailbox3,          /*494 Don't change this enum!!!*/
    ModuleId_Mailbox4,          /*495 Don't change this enum!!!*/
    ModuleId_Mailbox5,          /*496 Don't change this enum!!!*/
    ModuleId_Mailbox6,          /*497 Don't change this enum!!!*/
    ModuleId_Mailbox7,          /*498 Don't change this enum!!!*/
    ModuleId_Mailbox8,          /*499 Don't change this enum!!!*/
    ModuleId_Mailbox9,          /*500 Don't change this enum!!!*/
    ModuleId_Isp0,              /*501 Don't change this enum!!!*/
    ModuleId_Isp1,              /*502 Don't change this enum!!!*/
    ModuleId_Mipidsi0,          /*503 Don't change this enum!!!*/
    ModuleId_Mipidsi1,          /*504 Don't change this enum!!!*/
    ModuleId_Mipirx0,           /*505 Don't change this enum!!!*/
    ModuleId_Mipirx1,           /*506 Don't change this enum!!!*/
    ModuleId_Mipirx2,           /*507 Don't change this enum!!!*/
    ModuleId_Mipirx3,           /*508 Don't change this enum!!!*/
    ModuleId_Mipirx4,           /*509 Don't change this enum!!!*/
    ModuleId_Mipirx5,           /*510 Don't change this enum!!!*/
    ModuleId_Mipitxcsi0,        /*511 Don't change this enum!!!*/
    ModuleId_Mipitxcsi1,        /*512 Don't change this enum!!!*/
    ModuleId_Noc0,              /*513 Don't change this enum!!!*/
    ModuleId_Noc1,              /*514 Don't change this enum!!!*/
    ModuleId_Noc2,              /*515 Don't change this enum!!!*/
    ModuleId_Noc3,              /*516 Don't change this enum!!!*/
    ModuleId_Noc4,              /*517 Don't change this enum!!!*/
    ModuleId_Noc5,              /*518 Don't change this enum!!!*/
    ModuleId_Noc6,              /*519 Don't change this enum!!!*/
    ModuleId_Noc7,              /*520 Don't change this enum!!!*/
    ModuleId_Noc8,              /*521 Don't change this enum!!!*/
    ModuleId_Noc9,              /*522 Don't change this enum!!!*/
    ModuleId_Noc10,             /*523 Don't change this enum!!!*/
    ModuleId_Noc11,             /*524 Don't change this enum!!!*/
    ModuleId_Noc12,             /*525 Don't change this enum!!!*/
    ModuleId_Noc13,             /*526 Don't change this enum!!!*/
    ModuleId_Noc14,             /*527 Don't change this enum!!!*/
    ModuleId_Noc15,             /*528 Don't change this enum!!!*/
    ModuleId_Noc16,             /*529 Don't change this enum!!!*/
    ModuleId_Noc17,             /*530 Don't change this enum!!!*/
    ModuleId_Noc18,             /*531 Don't change this enum!!!*/
    ModuleId_Noc19,             /*532 Don't change this enum!!!*/
    ModuleId_Noc20,             /*533 Don't change this enum!!!*/
    ModuleId_Noc21,             /*534 Don't change this enum!!!*/
    ModuleId_Noc22,             /*535 Don't change this enum!!!*/
    ModuleId_Noc23,             /*536 Don't change this enum!!!*/
    ModuleId_Noc24,             /*537 Don't change this enum!!!*/
    ModuleId_Noc25,             /*538 Don't change this enum!!!*/
    ModuleId_Noc26,             /*539 Don't change this enum!!!*/
    ModuleId_Noc27,             /*540 Don't change this enum!!!*/
    ModuleId_Noc28,             /*541 Don't change this enum!!!*/
    ModuleId_Noc29,             /*542 Don't change this enum!!!*/
    ModuleId_Noc30,             /*543 Don't change this enum!!!*/
    ModuleId_Noc31,             /*544 Don't change this enum!!!*/
    ModuleId_Noc32,             /*545 Don't change this enum!!!*/
    ModuleId_Noc33,             /*546 Don't change this enum!!!*/
    ModuleId_Noc34,             /*547 Don't change this enum!!!*/
    ModuleId_Noc35,             /*548 Don't change this enum!!!*/
    ModuleId_Pcie0,             /*549 Don't change this enum!!!*/
    ModuleId_Pcie1,             /*550 Don't change this enum!!!*/
    ModuleId_Pvt0,              /*551 Don't change this enum!!!*/
    ModuleId_Pvt1,              /*552 Don't change this enum!!!*/
    ModuleId_Pvt2,              /*553 Don't change this enum!!!*/
    ModuleId_Pvt3,              /*554 Don't change this enum!!!*/
    ModuleId_R52core0,          /*555 Don't change this enum!!!*/
    ModuleId_R52core1,          /*556 Don't change this enum!!!*/
    ModuleId_R52core2,          /*557 Don't change this enum!!!*/
    ModuleId_R52core3,          /*558 Don't change this enum!!!*/
    ModuleId_R52core4,          /*559 Don't change this enum!!!*/
    ModuleId_Emmc0,             /*560 Don't change this enum!!!*/
    ModuleId_Emmc1,             /*561 Don't change this enum!!!*/
    ModuleId_Smmu0,             /*562 Don't change this enum!!!*/
    ModuleId_Smmu1,             /*563 Don't change this enum!!!*/
    ModuleId_Smmu2,             /*564 Don't change this enum!!!*/
    ModuleId_Smmu3,             /*565 Don't change this enum!!!*/
    ModuleId_Smmu4,             /*566 Don't change this enum!!!*/
    ModuleId_Smmu5,             /*567 Don't change this enum!!!*/
    ModuleId_Smmu6,             /*568 Don't change this enum!!!*/
    ModuleId_Smmu7,             /*569 Don't change this enum!!!*/
    ModuleId_Spi0,              /*570 Don't change this enum!!!*/
    ModuleId_Spi1,              /*571 Don't change this enum!!!*/
    ModuleId_Spi2,              /*572 Don't change this enum!!!*/
    ModuleId_Spi3,              /*573 Don't change this enum!!!*/
    ModuleId_Spi4,              /*574 Don't change this enum!!!*/
    ModuleId_Spi5,              /*575 Don't change this enum!!!*/
    ModuleId_Spi6,              /*576 Don't change this enum!!!*/
    ModuleId_Spi7,              /*577 Don't change this enum!!!*/
    ModuleId_Spi8,              /*578 Don't change this enum!!!*/
    ModuleId_Spi9,              /*579 Don't change this enum!!!*/
    ModuleId_Spi10,             /*580 Don't change this enum!!!*/
    ModuleId_Spi11,             /*581 Don't change this enum!!!*/
    ModuleId_Spi12,             /*582 Don't change this enum!!!*/
    ModuleId_Spi13,             /*583 Don't change this enum!!!*/
    ModuleId_Uart0,             /*584 Don't change this enum!!!*/
    ModuleId_Uart1,             /*585 Don't change this enum!!!*/
    ModuleId_Uart2,             /*586 Don't change this enum!!!*/
    ModuleId_Uart3,             /*587 Don't change this enum!!!*/
    ModuleId_Hsm0,              /*588 Don't change this enum!!!*/
    ModuleId_Hsm1,              /*589 Don't change this enum!!!*/
    ModuleId_Hsm2,              /*590 Don't change this enum!!!*/
    ModuleId_Hsm3,              /*591 Don't change this enum!!!*/
    ModuleId_Hsm4,              /*592 Don't change this enum!!!*/
    ModuleId_Hsm5,              /*593 Don't change this enum!!!*/
    ModuleId_Hsm6,              /*594 Don't change this enum!!!*/
    ModuleId_Hsm7,              /*595 Don't change this enum!!!*/
    ModuleId_Hsm8,              /*596 Don't change this enum!!!*/
    ModuleId_Hsm9,              /*597 Don't change this enum!!!*/
    ModuleId_Hsm10,             /*598 Don't change this enum!!!*/
    ModuleId_Hsm11,             /*599 Don't change this enum!!!*/
    ModuleId_Hsm12,             /*600 Don't change this enum!!!*/
    ModuleId_Vdsp0,             /*601 Don't change this enum!!!*/
    ModuleId_Vdsp1,             /*602 Don't change this enum!!!*/
    ModuleId_Wwdt0,             /*603 Don't change this enum!!!*/
    ModuleId_Wwdt1,             /*604 Don't change this enum!!!*/
    ModuleId_Wwdt2,             /*605 Don't change this enum!!!*/
    ModuleId_Wwdt3,             /*606 Don't change this enum!!!*/
    ModuleId_Wwdt4,             /*607 Don't change this enum!!!*/
    ModuleId_Wwdt5,             /*608 Don't change this enum!!!*/
    ModuleId_Wwdt6,             /*609 Don't change this enum!!!*/
    ModuleId_Wwdt7,             /*610 Don't change this enum!!!*/
    ModuleId_Wwdt8,             /*611 Don't change this enum!!!*/
    ModuleId_Wwdt9,             /*612 Don't change this enum!!!*/
    ModuleId_Wwdt10,            /*613 Don't change this enum!!!*/
    ModuleId_Wwdt11,            /*614 Don't change this enum!!!*/
    ModuleId_Wwdt12,            /*615 Don't change this enum!!!*/
    ModuleId_Wwdt13,            /*616 Don't change this enum!!!*/
    ModuleId_Wwdt14,            /*617 Don't change this enum!!!*/
    ModuleId_Wwdt15,            /*618 Don't change this enum!!!*/
    ModuleId_Wwdt16,            /*619 Don't change this enum!!!*/
    ModuleId_Wwdt17,            /*620 Don't change this enum!!!*/
    ModuleId_Wwdt18,            /*621 Don't change this enum!!!*/
    ModuleId_Wwdt19,            /*622 Don't change this enum!!!*/
    ModuleId_Xspi0,             /*623 Don't change this enum!!!*/
    ModuleId_Gdc0,              /*624 Don't change this enum!!!*/
    ModuleId_Gdc1,              /*625 Don't change this enum!!!*/
    ModuleId_Pmic0,             /*626 Don't change this enum!!!*/
    ModuleId_IntRouter0,        /*627 Don't change this enum!!!*/
    ModuleId_IntRouter1,        /*628 Don't change this enum!!!*/
    ModuleId_IntRouter2,        /*629 Don't change this enum!!!*/
    ModuleId_IntRouter3,        /*630 Don't change this enum!!!*/
    ModuleId_IntRouter4,        /*631 Don't change this enum!!!*/
    ModuleId_IntRouter5,        /*632 Don't change this enum!!!*/
    ModuleId_IntRouter6,        /*633 Don't change this enum!!!*/
    ModuleId_IntRouter7,        /*634 Don't change this enum!!!*/
    ModuleId_IntRouter8,        /*635 Don't change this enum!!!*/
    ModuleId_IntRouter9,        /*636 Don't change this enum!!!*/
    ModuleId_IntRouter10,       /*637 Don't change this enum!!!*/
    ModuleId_IntRouter11,       /*638 Don't change this enum!!!*/
    ModuleId_IntRouter12,       /*639 Don't change this enum!!!*/
    ModuleId_IntRouter13,       /*640 Don't change this enum!!!*/
    ModuleId_IntRouter14,       /*641 Don't change this enum!!!*/
    ModuleId_IntRouter15,       /*642 Don't change this enum!!!*/
    ModuleId_IntRouter16,       /*643 Don't change this enum!!!*/
    ModuleId_IntRouter17,       /*644 Don't change this enum!!!*/
    ModuleId_IntRouter18,       /*645 Don't change this enum!!!*/
    ModuleId_IntRouter19,       /*646 Don't change this enum!!!*/
    ModuleId_IntRouter20,       /*647 Don't change this enum!!!*/
    ModuleId_IntRouter21,       /*648 Don't change this enum!!!*/
    ModuleId_IntRouter22,       /*649 Don't change this enum!!!*/
    ModuleId_IntRouter23,       /*650 Don't change this enum!!!*/
    ModuleId_IntRouter24,       /*651 Don't change this enum!!!*/
    ModuleId_IntRouter25,       /*652 Don't change this enum!!!*/
    ModuleId_IntRouter26,       /*653 Don't change this enum!!!*/
    ModuleId_IntRouter27,       /*654 Don't change this enum!!!*/
    ModuleId_IntRouter28,       /*655 Don't change this enum!!!*/
    ModuleId_IntRouter29,       /*656 Don't change this enum!!!*/
    ModuleId_IntRouter30,       /*657 Don't change this enum!!!*/
    ModuleId_IntRouter31,       /*658 Don't change this enum!!!*/
    ModuleId_IntRouter32,       /*659 Don't change this enum!!!*/
    ModuleId_IntRouter33,       /*660 Don't change this enum!!!*/
    ModuleId_IntRouter34,       /*661 Don't change this enum!!!*/
    ModuleId_IntRouter35,       /*662 Don't change this enum!!!*/
    ModuleId_Pinctrl0,          /*663 Don't change this enum!!!*/
    ModuleId_Pinctrl1,          /*664 Don't change this enum!!!*/
    ModuleId_Pinctrl2,          /*665 Don't change this enum!!!*/
    ModuleId_Pinctrl3,          /*666 Don't change this enum!!!*/
    ModuleId_Pinctrl4,          /*667 Don't change this enum!!!*/
    ModuleId_Pinctrl5,          /*668 Don't change this enum!!!*/
    ModuleId_Rtc1,              /*669 Don't change this enum!!!*/
    ModuleId_Rtc2,              /*670 Don't change this enum!!!*/
    ModuleId_Rtc3,              /*671 Don't change this enum!!!*/
    ModuleId_Pinctrl6,          /*672 Don't change this enum!!!*/
    ModuleId_Pinctrl7,          /*673 Don't change this enum!!!*/
    ModuleId_Pinctrl8,          /*674 Don't change this enum!!!*/
    ModuleId_Pinctrl9,          /*675 Don't change this enum!!!*/
    ModuleId_Pinctrl10,         /*676 Don't change this enum!!!*/
    ModuleId_Pinctrl11,         /*677 Don't change this enum!!!*/
    ModuleId_Pinctrl12,         /*678 Don't change this enum!!!*/
    ModuleId_Pinctrl13,         /*679 Don't change this enum!!!*/
    ModuleId_Pinctrl14,         /*680 Don't change this enum!!!*/
    ModuleId_Pinctrl15,         /*681 Don't change this enum!!!*/
    ModuleId_Canfd2,            /*682 Don't change this enum!!!*/
    ModuleId_Canfd3,            /*683 Don't change this enum!!!*/
    ModuleId_Canfd4,            /*684 Don't change this enum!!!*/
    ModuleId_Canfd5,            /*685 Don't change this enum!!!*/
    ModuleId_Canfd6,            /*686 Don't change this enum!!!*/
    ModuleId_Canfd7,            /*687 Don't change this enum!!!*/
    ModuleId_Canfd8,            /*688 Don't change this enum!!!*/
    ModuleId_Canfd9,            /*689 Don't change this enum!!!*/
    ModuleId_Canfd10,           /*690 Don't change this enum!!!*/
    ModuleId_Canfd11,           /*691 Don't change this enum!!!*/
    ModuleId_Canfd12,           /*692 Don't change this enum!!!*/
    ModuleId_Canfd13,           /*693 Don't change this enum!!!*/
    ModuleId_Canfd14,           /*694 Don't change this enum!!!*/
    ModuleId_Canfd15,           /*695 Don't change this enum!!!*/
    ModuleId_Canfd16,           /*696 Don't change this enum!!!*/
    ModuleId_Canfd17,           /*697 Don't change this enum!!!*/
    ModuleId_Canfd18,           /*698 Don't change this enum!!!*/
    ModuleId_Canfd19,           /*699 Don't change this enum!!!*/
    ModuleId_Canfd20,           /*700 Don't change this enum!!!*/
    ModuleId_Canfd21,           /*701 Don't change this enum!!!*/
    ModuleId_Canfd22,           /*702 Don't change this enum!!!*/
    ModuleId_Canfd23,           /*703 Don't change this enum!!!*/
    ModuleId_Gpio4,             /*704 Don't change this enum!!!*/
    ModuleId_Gpio5,             /*705 Don't change this enum!!!*/
    ModuleId_Gpio6,             /*706 Don't change this enum!!!*/
    ModuleId_Gpio7,             /*707 Don't change this enum!!!*/
    ModuleId_Gpio8,             /*708 Don't change this enum!!!*/
    ModuleId_Gpio9,             /*709 Don't change this enum!!!*/
    ModuleId_Gpio10,            /*710 Don't change this enum!!!*/
    ModuleId_Gpio11,            /*711 Don't change this enum!!!*/
    ModuleId_Gpio12,            /*712 Don't change this enum!!!*/
    ModuleId_Gpio13,            /*713 Don't change this enum!!!*/
    ModuleId_Gpio14,            /*714 Don't change this enum!!!*/
    ModuleId_Gpio15,            /*715 Don't change this enum!!!*/
    ModuleId_Isp2,              /*716 Don't change this enum!!!*/
    ModuleId_Isp3,              /*717 Don't change this enum!!!*/
    ModuleId_Isp4,              /*718 Don't change this enum!!!*/
    ModuleId_Isp5,              /*719 Don't change this enum!!!*/
    ModuleId_Pmic1,             /*720 Don't change this enum!!!*/
    ModuleId_Pmic2,             /*721 Don't change this enum!!!*/
    ModuleId_Pmic3,             /*722 Don't change this enum!!!*/
    ModuleId_Pmic4,             /*723 Don't change this enum!!!*/
    ModuleId_Pmic5,             /*724 Don't change this enum!!!*/
    ModuleId_Pmic6,             /*725 Don't change this enum!!!*/
    ModuleId_Pmic7,             /*726 Don't change this enum!!!*/
    ModuleId_Uart4,             /*727 Don't change this enum!!!*/
    ModuleId_Uart5,             /*728 Don't change this enum!!!*/
    ModuleId_Uart6,             /*729 Don't change this enum!!!*/
    ModuleId_Uart7,             /*730 Don't change this enum!!!*/
    ModuleId_Uart8,             /*731 Don't change this enum!!!*/
    ModuleId_Uart9,             /*732 Don't change this enum!!!*/
    ModuleId_Display0,          /*733 Don't change this enum!!!*/
    ModuleId_Display1,          /*734 Don't change this enum!!!*/
    ModuleId_Max      = 735,    /*735 Don't change this enum!!!*/
    ModuleDiag_KernelMax = 0x0FFF,
    ALL_ModuleIdMax = 0xFFFF,
}Hobot_ModuleId;


/** @brief Autogen:typedef_EventId */
typedef enum {
    EventId_Invalid     =  0,    /*0 Don't change this enum!!!*/
    EventId_ParityErr   =  1,    /*1 Don't change this enum!!!*/
    EventId_LockstepErr,        /*2 Don't change this enum!!!*/
    EventId_RBackErr,           /*3 Don't change this enum!!!*/
    EventId_Ecc1BitErr,         /*4 Don't change this enum!!!*/
    EventId_Ecc2BitErr,         /*5 Don't change this enum!!!*/
    EventId_IntMisinfoErr,      /*6 Don't change this enum!!!*/
    EventId_IntLatentErr,       /*7 Don't change this enum!!!*/
    EventId_SetInfoErr,         /*8 Don't change this enum!!!*/
    EventId_GetInfoErr,         /*9 Don't change this enum!!!*/
    EventId_TimeoutErr,         /*10 Don't change this enum!!!*/
    EventId_CheckErr,           /*11 Don't change this enum!!!*/
    EventId_StartErr,           /*12 Don't change this enum!!!*/
    EventId_StopErr,            /*13 Don't change this enum!!!*/
    EventId_CalcErr,            /*14 Don't change this enum!!!*/
    EventId_FetchResourceErr,    /*15 Don't change this enum!!!*/
    EventId_OpenCreateErr,      /*16 Don't change this enum!!!*/
    EventId_CloseDestroyErr,    /*17 Don't change this enum!!!*/
    EventId_HardwareStatusErr,    /*18 Don't change this enum!!!*/
    EventId_DataErr,            /*19 Don't change this enum!!!*/
    EventId_BusHangErr,         /*20 Don't change this enum!!!*/
    EventId_AuthorityErr,       /*21 Don't change this enum!!!*/
    EventId_OutOfRangeErr,      /*22 Don't change this enum!!!*/
    EventId_SendErr,            /*23 Don't change this enum!!!*/
    EventId_RecvErr,            /*24 Don't change this enum!!!*/
    EventId_InjectErr,          /*25 Don't change this enum!!!*/
    EventId_ResourceErr,        /*26 Don't change this enum!!!*/
    EventId_SequenceErr,        /*27 Don't change this enum!!!*/
    EventId_IrqErr,             /*28 Don't change this enum!!!*/
    EventId_LostHeartErr,       /*29 Don't change this enum!!!*/
    EventId_VoltageErr,         /*30 Don't change this enum!!!*/
    EventId_TempratureErr,      /*31 Don't change this enum!!!*/
    EventId_AckErr,             /*32 Don't change this enum!!!*/
    EventId_ProtocolErr,        /*33 Don't change this enum!!!*/
    EventId_DmaErr,             /*34 Don't change this enum!!!*/
    EventId_FifoErr,            /*35 Don't change this enum!!!*/
    EventId_IPStatusMismatchErr,    /*36 Don't change this enum!!!*/
    EventId_NocErr,             /*37 Don't change this enum!!!*/
    EventId_TopErr,             /*38 Don't change this enum!!!*/
    EventId_WdtRstErr,          /*39 Don't change this enum!!!*/
    EventId_DoubleTypeErr,      /*40 Don't change this enum!!!*/
    EventId_Vdsp0SoftErr,       /*41 Don't change this enum!!!*/
    EventId_Vdsp1SoftErr,       /*42 Don't change this enum!!!*/
    EventId_RASDPErr,           /*43 Don't change this enum!!!*/
    EventId_LinkStatErr,        /*44 Don't change this enum!!!*/
    EventId_RSErr,              /*45 Don't change this enum!!!*/
    EventId_RegAcessErr,        /*46 Don't change this enum!!!*/
    EventId_AerCorErr,          /*47 Don't change this enum!!!*/
    EventId_AerUnCorErr,        /*48 Don't change this enum!!!*/
    EventId_DualCheckErr,       /*49 Don't change this enum!!!*/
    EventId_UnregisterHandler,    /*50 Don't change this enum!!!*/
    EventId_SelfcheckFail,      /*51 Don't change this enum!!!*/
    EventId_R52PErr,            /*52 Don't change this enum!!!*/
    EventId_A78AeErr,           /*53 Don't change this enum!!!*/
    EventId_ClearErr,           /*54 Don't change this enum!!!*/
    EventId_BpuErr,             /*55 Don't change this enum!!!*/
    EventId_PeriodCheckFail,    /*56 Don't change this enum!!!*/
    EventId_Max       =  57,    /*57 Don't change this enum!!!*/
}Hobot_EventId;
#endif /*ifndef DIAG_ID_H_*/
